# -*- coding: utf-8 -*-
"""Lektion-2-ml.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15yYxHYq308NDer_8iIckRbKxSFszuG_H
"""

# Imports the pandas library and loads a wine quality dataset from GitHub into a DataFrame called df
import pandas as pd

# data loading

# loading raw data into python environment
url = "https://raw.githubusercontent.com/joneikholmkea/machine-learning/main/spring26/lektion2/Wine_quality.csv"
df = pd.read_csv(url)

df.head()

X = df.drop(columns=["Id","quality"])

X

y = df["quality"]

y

X.shape

y.shape

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.2, random_state=42)

y_test

from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)

X_test = scaler.transform(X_test)

X_test

import tensorflow as tf
from tensorflow.keras.layers import Dense, Activation

model = keras.Sequential([
    Dense(64, activation="tanh", input_shape = (X_train.shape[1],)),
    Dense(32, activation="tanh"),
    Dense(32, activation="tanh"),
    Dense(1, activation="sigmoid")
])

model.compile(
    optimizer="adam",
    loss="binary_crossentropy",
    metrics=["accuracy"]
)

model.summary()

model.fit(
    X_train,
    y_train,
    epochs=20,
    validation_split=0.2,
    verbose=1
)

